eureka:
  client:
    register-with-eureka: false  # Si tu ne veux pas enregistrer le gateway dans Eureka


server:
  port: 8222  # Port du gateway


spring:
  application:
    name: gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Active la découverte dynamique des services via Eureka
      routes:
        - id: students
          uri: http://localhost:8081
          predicates:
            - Path=/students/**


        - id: companies
          uri: http://localhost:8082
          predicates:
            - Path=/companies/**
