// src/app/enums/domaine.enum.ts

export enum Domaine {
  TELECOM = 'TELECOM',
  NETWORK = 'NETWORK',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  CLOUD = 'CLOUD',
  ENERGY = 'ENERGY',
  EDUCATION = 'EDUCATION',
  PHP_PROGRAMMING = 'PHP_PROGRAMMING',
  WEB_DESIGNER = 'WEB_DESIGNER',
  GRAPHIC_DESIGNER = 'GRAPHIC_DESIGNER',
  OFFICE = 'OFFICE',
  SOFTWARE_DEVELOPMENT = 'SOFTWARE_DEVELOPMENT',
  PROJECT_MANAGEMENT = 'PROJECT_MANAGEMENT',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  MULTIMEDIA = 'MULTIMEDIA',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  MARKETING = 'MARKETING'
}
