package com.esprit.user.enums;

public enum Domaine {
    TELECOM,NETWORK, WEB_DEVELOPMENT, CLOUD ,ENERGY,EDUCATION,PHP_PROGRAMMING,WEB_DESIGNER,GRAPHIC_DESIGNER,OFFICE,SOFTWARE_DEVELOPMENT,
    PROJECT_MANAGMENT,CUSTOMER_SERIVCE,MULTIMEDIA,SOCIAL_MEDIA,MARKETING
}
