eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



server:
  port: 8082

spring:
  application:
    name: companies

  datasource:
    url: jdbc:mysql://localhost:3306/companies?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  config:
    students-url: http://localhost:8081/students



