variables:
  DOCKER_HUB_IMAGE: salimbouazizi/memmi02
  DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD

# Declare the stages in the correct order
stages:
  - build
  - docker-build
  - deploy

# Step 1: Build Angular Project
build-frontend:
  stage: build
  image: node:16
  script:
    - npm ci --legacy-peer-deps
    - npm run build --prod
  artifacts:
    paths:
      - dist/

# Step 2: Build Docker Image and Push to Docker Hub
docker-build-and-push:
  stage: docker-build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker build -t $DOCKER_HUB_IMAGE .
    - docker image ls
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push $DOCKER_HUB_IMAGE
  only:
    - master

# Step 3: Update Deployment YAML with the Latest Image
update-deployment:
  stage: deploy
  image: alpine:3.18
  script:
    - apk add --no-cache yq
    - yq -i '.spec.template.spec.containers[0].image = env(DOCKER_HUB_IMAGE)' angular-deployment.yaml
    - cat angular-deployment.yaml  # Output the updated deployment file for verification
  dependencies:
    - docker-build-and-push
  only:
    - master


