eureka:
  client:
    enabled: true  # Enable Eureka client
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: internships
          uri: lb://internship  # Use Eureka service name
          predicates:
            - Path=/api/internships/**
